title: Adi Sarwaikar
logo: assets/img/pfp.jpg
description: Hi! My name is Aditya Sarwaikar, and I am pursuing an Aerospace & Aeronautical Engineering degree at Purdue University. This is my project portfolio.
show_downloads: false
theme: jekyll-theme-minimal
